apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dev-go-pod
  name: dev-go-pod
spec:
  containers:
  - command:
    - /bin/start-script.sh /bin/bash
    env:
    - name: TERM
      value: xterm
    - name: WAYLAND_DISPLAY
      value: wayland-1
    - name: XDG_RUNTIME_DIR
      value: /run/user/1001
    - name: HOME
      value: /home/tr-dev-go-pod
    image: localhost/thinbase:latest
    name: dev-go-container
    stdin: true
    tty: true
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /run/user/1001/wayland-1
      name: run-user-1001-wayland-1-host-0
    - mountPath: /run/user/1001/pulse
      name: run-user-1001-pulse
    - mountPath: /home/tr-dev-go-pod
      name: home-dir
    - mountPath: /etc/ssl
      name: etc-ssl-host-2
      readOnly: true
    - mountPath: /etc/static/ssl
      name: etc-static-ssl-host-3
    - mountPath: /nix/store/bzyihlr7n1gg9hlkdhilxsh7a4qi9ipx-nss-cacert-3.108/etc/ssl/certs/ca-bundle.crt
      name: nss-cacert
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /run/user/1001/wayland-1
      type: File
    name: run-user-1001-wayland-1-host-0
  - hostPath:
      path: /run/user/1001/pulse
      type: Directory
    name: run-user-1001-pulse
  - hostPath:
      path: /home/tr/container-data/dev/go/home/tr
      type: Directory
    name: home-dir
  - hostPath:
      path: /etc/ssl
      type: Directory
    name: etc-ssl-host-2
  - hostPath:
      path: /etc/static/ssl
      type: Directory
    name: etc-static-ssl-host-3
  - hostPath:
      path: /nix/store/bzyihlr7n1gg9hlkdhilxsh7a4qi9ipx-nss-cacert-3.108/etc/ssl/certs/ca-bundle.crt
      type: File
    name: nss-cacert

